### ISSUE TITLE
Cannot call merchant/orders/list/<status> endpoint

### ISSUE THREAD

**Issue by vasudharsai** [sifourteen/cartrover-ruby-client#1]
Hi whenever I make API call to "https://api.cartrover.com/v1/merchant/orders/list/new?api_user=myapiuser&api_key=myapikey" kit returns error: Missing or invalid parameter: merchant required.
In the documentation the request is mentioned as GET and not no sign of how to send merchant ID, Name with the request

**Comment by JaggedJax** [comment]
Make sure you are using API credentials provided from the Merchant page, and not from the WMS setup page. If you only have WMS keys, you can manually create merchant keys from the UI or perform a New Merchant API call to create the merchant and get API keys for it at the same time.

**Comment by vasudharsai** [comment]
Gotcha.. Thank you !!

**Comment by luishs0** [comment]
Hi, how can i set a new merchant with the API? I only see in the documentation to set up carts

**Comment by JaggedJax** [comment]
Hi @luishs0 To create a New Merchant you'll need to have either a Warehouse or Master level account.
If you have a Warehouse level account, you can use your Warehouse level API credentials to create a new merchant using this endpoint: https://developers.cartrover.com/#eb0245bf-0ce2-4fdb-a9d3-c6cbab6aa48c

If you have a Master level account with Master level API credentials, you can use this endpoint to create a new merchant Sub-Account: https://developers.cartrover.com/#9141a404-0777-449d-8660-170cb23c66d7

If you currently have a Merchant account, you cannot create a new Merchant through the API and would need to sign up for a new Merchant account r request support to upgrade your Merchant account to a Warehouse account.

I don't believe this library has those calls explicitly implemented, but you can still use it to make the calls as documented above.
